export const actionTypes = {
    FETCHING_START: "FETCHING_START",
    FETCHING_SUCCESS: "FETCHING_SUCCESS",
    FETCHING_ERROR: "FETCHING_ERROR",
    SINGLE_FETCHING_START: "SINGLE_FETCHING_START",
    SINGLE_FETCHING_SUCCESS: "SINGLE_FETCHING_SUCCESS",
    SINGLE_FETCHING_ERROR: "SINGLE_FETCHING_ERROR",
    
}