export const coursesActionTypes = {
    FETCHING_START: "FETCHING_START",
    FETCHING_SUCCESS: "FETCHING_SUCCESS",
    FETCHING_ERROR: "FETCHING_ERROR",
    SINGLE_FETCHING_START: "SINGLE_FETCHING_START",
    SINGLE_FETCHING_SUCCESS: "SINGLE_FETCHING_SUCCESS",
    SINGLE_FETCHING_ERROR: "SINGLE_FETCHING_ERROR",
    
}
export const testimonialActionTypes = {
    START: "START",
    SUCCESS: "SUCCESS",
    ERROR: "ERROR",
}
export const blogActionTypes = {
    START_FETCHING: "START_FETCHING",
    SUCCESS_FETCHING: "SUCCESS_FETCHING",
    ERROR_FETCHING: "ERROR_FETCHING",
}